# ClinicScreen - one-shot local setup for Windows.
#
# Run this from a PowerShell window after cloning the repo:
#
#     powershell -ExecutionPolicy Bypass -File scripts\setup.ps1
#
# It checks prerequisites, creates the local database, writes a .env, installs
# dependencies, applies migrations, (optionally) loads demo data, and can start
# the app. When it's done you sign in with the "Developer sign-in" button - no
# auth server or secrets required.

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

function Info($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "    $m" -ForegroundColor Green }
function Warn($m) { Write-Host "    $m" -ForegroundColor Yellow }
function Fail($m) { Write-Host "ERROR: $m" -ForegroundColor Red; exit 1 }

Write-Host ""
Write-Host "ClinicScreen local setup" -ForegroundColor White
Write-Host "------------------------" -ForegroundColor White

# --- 1. Node -----------------------------------------------------------------
Info "Checking Node.js"
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) {
  Warn "Node.js is not installed."
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    Info "Installing Node.js via winget (approve any prompt)..."
    winget install --id OpenJS.NodeJS --accept-source-agreements --accept-package-agreements
    Warn "Node was just installed. CLOSE this window, open a NEW PowerShell, and run this script again."
    exit 0
  }
  Fail "Install Node.js 20+ from https://nodejs.org (LTS), then re-run this script."
}
$nodeMajor = ((node -v) -replace "[^\d.]", "").Split(".")[0] -as [int]
if ($nodeMajor -lt 18) { Fail "Node $(node -v) is too old. Install Node 20+ from https://nodejs.org." }
Ok "Node $(node -v)"

# --- 2. PostgreSQL (psql) ----------------------------------------------------
Info "Checking PostgreSQL"
$psql = (Get-Command psql -ErrorAction SilentlyContinue).Source
if (-not $psql) {
  $cand = Get-ChildItem "C:\Program Files\PostgreSQL\*\bin\psql.exe" -ErrorAction SilentlyContinue |
    Sort-Object FullName -Descending | Select-Object -First 1
  if ($cand) { $psql = $cand.FullName }
}
if (-not $psql) {
  Warn "PostgreSQL is not installed (psql not found)."
  if (Get-Command winget -ErrorAction SilentlyContinue) {
    Info "Installing PostgreSQL via winget (approve any prompt; note the password you set)..."
    winget install --id PostgreSQL.PostgreSQL.17 --accept-source-agreements --accept-package-agreements
    Warn "PostgreSQL was just installed. CLOSE this window, open a NEW PowerShell, and run this script again."
    exit 0
  }
  Fail "Install PostgreSQL 17 from https://www.postgresql.org/download/windows/, then re-run this script."
}
Ok "psql found: $psql"

# --- 3. Database connection --------------------------------------------------
Info "Database connection"
$dbUser = "postgres"
$dbHost = "localhost"
$dbPort = "5432"
$dbName = "carescreen"
$pwPlain = Read-Host "Postgres password for user '$dbUser' (press Enter for 'postgres')"
if ([string]::IsNullOrWhiteSpace($pwPlain)) { $pwPlain = "postgres" }
$env:PGPASSWORD = $pwPlain

# Verify we can connect before going further.
& $psql -U $dbUser -h $dbHost -p $dbPort -d postgres -tAc "SELECT 1" *> $null
if ($LASTEXITCODE -ne 0) {
  Fail "Could not connect to Postgres as '$dbUser'. Check that the service is running and the password is correct."
}
Ok "Connected to Postgres"

# --- 4. Create the database --------------------------------------------------
Info "Ensuring database '$dbName' exists"
$exists = & $psql -U $dbUser -h $dbHost -p $dbPort -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$dbName'"
if ($exists.Trim() -eq "1") {
  Ok "Database already exists"
} else {
  & $psql -U $dbUser -h $dbHost -p $dbPort -d postgres -c "CREATE DATABASE $dbName" *> $null
  if ($LASTEXITCODE -ne 0) { Fail "Failed to create database '$dbName'." }
  Ok "Created database '$dbName'"
}

# --- 5. .env -----------------------------------------------------------------
Info "Writing .env"
$databaseUrl = "postgresql://${dbUser}:${pwPlain}@${dbHost}:${dbPort}/${dbName}?schema=public"
$sessionSecret = [Convert]::ToBase64String([byte[]](1..48 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 }))
$envPath = Join-Path $RepoRoot ".env"
if (Test-Path $envPath) {
  Warn ".env already exists - leaving it as-is (delete it and re-run to regenerate)."
} else {
  $envLines = @(
    "# Generated by scripts/setup.ps1",
    "DATABASE_URL=`"$databaseUrl`"",
    "SESSION_SECRET=`"$sessionSecret`"",
    "",
    "# Local dev sign-in (Developer sign-in button on the login page).",
    "DEV_LOGIN=`"1`"",
    "",
    "# Optional: add your own Anthropic key to enable doctor scraping + AI intros.",
    "ANTHROPIC_API_KEY=`"`"",
    "",
    "# quickAuth is not used in dev-login mode; placeholders are fine.",
    "QUICKAUTH_URL=`"http://localhost:3000`"",
    "QUICKAUTH_CLIENT_ID=`"qa_client_dev`"",
    "QUICKAUTH_CLIENT_SECRET=`"qa_secret_dev`"",
    "QUICKAUTH_REDIRECT_URI=`"http://localhost:3001/auth/callback`"",
    "QUICKAUTH_PROVISION_SECRET=`"dev`"",
    "",
    "# Media stored on local disk in dev (leave R2 blank).",
    "R2_ACCOUNT_ID=`"`"",
    "R2_ACCESS_KEY_ID=`"`"",
    "R2_SECRET_ACCESS_KEY=`"`"",
    "R2_BUCKET=`"`"",
    "R2_PUBLIC_URL=`"`""
  )
  # ASCII, no BOM - so dotenv reads the first key cleanly.
  Set-Content -Path $envPath -Value $envLines -Encoding ascii
  Ok "Wrote .env (DEV_LOGIN enabled, random session secret)"
}

# --- 6. Dependencies ---------------------------------------------------------
Info "Installing dependencies (npm install) - this can take a few minutes"
npm install
if ($LASTEXITCODE -ne 0) { Fail "npm install failed." }
Ok "Dependencies installed"

# --- 7. Database schema ------------------------------------------------------
Info "Applying database migrations"
npx prisma migrate deploy
if ($LASTEXITCODE -ne 0) { Fail "prisma migrate deploy failed." }
npx prisma generate | Out-Null
Ok "Schema applied and Prisma client generated"

# --- 8. Optional demo data ---------------------------------------------------
$seed = Read-Host "Load demo data (a sample practice + screens)? [y/N]"
if ($seed -match '^(y|yes)$') {
  Info "Seeding demo data"
  npm run db:seed
  if ($LASTEXITCODE -ne 0) { Warn "Seeding failed - you can still create data by hand." }
  else { Ok "Demo data loaded" }
}

# --- 9. Done -----------------------------------------------------------------
Write-Host ""
Write-Host "Setup complete." -ForegroundColor Green
Write-Host "  1. Start the app:   npm run dev" -ForegroundColor White
Write-Host "  2. Open:            http://localhost:3001" -ForegroundColor White
Write-Host "  3. Click 'Developer sign-in' to log in as a local admin." -ForegroundColor White
Write-Host ""
$run = Read-Host "Start the app now (npm run dev)? [Y/n]"
if ($run -notmatch '^(n|no)$') {
  Info "Starting dev server on http://localhost:3001 (Ctrl+C to stop)"
  npm run dev
}
